# Generated by Django 5.2 on 2025-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serlization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
